### ISSUE TITLE
missing script start

### ISSUE THREAD

**Issue by hwaynefair** [autopulous/angular2-soap#2]
Attempting to get this to run on Windows 10 using Visual Studio Code and built in Terminal- I confess **_extreme_** ignorance - but I followed your "Usage" directions 2 times - and always got the same errors in the log file.
Please advise - thanks!
[npm-debug - Copy.txt](https://github.com/autopulous/angular2-soap/files/367875/npm-debug.-.Copy.txt)

**Comment by autopulous** [comment]
I just posted an update that hopefully corrects/clarifies the (former) usage instructions... if your intent is to simply use the SOAP client you just want to include the package in your project and then call it. (I've attached an Angular2 class that wraps this package allowing a developer to inject this wrapper service (and subsequently this Angular2 SOAP package) into their application

[soap.service.txt](https://github.com/autopulous/angular2-soap/files/369798/soap.service.txt)

Note: rename the file extension from .txt to .ts --- so the Typescript compiler will recognize the file.

**Comment by autopulous** [comment]
To specifically address the issue that you were having, Yes the "start" script was removed from the package - the "unit test continuously" npm script took it's place

To execute this script enter the following at the command line:

npm run "unit test continuously"

There are many possible ways to manage a development build/test cycle, so these scripts are just examples - I still have a lot to learn myself - and as such as I tinker I change (and break things) - I appreciate you bring my omission to my attention - it's nice to know that there's some interest out there for my stuff - if you need any help with this or have any suggestions please let me know I'll try to get back to you in no more than a day (most of the time)

**Comment by hwaynefair** [comment]
Thanks so much, John! That did it - it is running now... I am specifically trying to do some experimental implementation of SOAP using Angular2 for the Blackbaud API. I really appreciate your help and friendly response!
